version: '3.4'
services:
  onesignal-web-sdk-dev:
      image: onesignal/web-sdk-dev
      container_name: web-sdk-dev
      build: .
      volumes:
        - .:/sdk:cached
        - sdk-build:/sdk/build/releases

# Named volumes that are persisted between docker-compose rebuilds.
# If you need to remove these volumes for some reason, run `docker-compose down -v`
volumes:
  sdk-build:
    name: web-sdk_build