graph TB
  subgraph SubscriptionManager
    subscribe
    doPushSubscribe
    registerSubscription
    
    subscribe-->doPushSubscribe
  end

  subgraph SubscriptionHelper.internalRegisterForPush
    subscriptionManager.subscribe
    subscriptionManager.registerSubscription
    rawSubscription([rawSubscription])
    
    doPushSubscribe-. return RawPushSubscription .->rawSubscription
    rawSubscription-->subscriptionManager.registerSubscription
    subscriptionManager.subscribe-->subscribe
    subscriptionManager.registerSubscription-->registerSubscription
  end

  subgraph UpdateManager
    sendPlayerUpdate

    registerSubscription-->sendPlayerUpdate
    sendPlayerUpdate-->onSessionSent
    onSessionSent{onSessionSent}
      onSessionSent-- Yes --> OneSignalApiShared.updatePlayer
      onSessionSent-- No --> sendOnSessionUpdate
  end

  subgraph OneSignalApiShared
    updatePlayer
    OneSignalApiShared.updatePlayer-->updatePlayer
  end