// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/52410f6f389586942d6427bbf66ac2bf4a9cf04b/es6-error/es6-error.d.ts
declare module "es6-error" {
    export = Error
}
