name: 📣 General feedback
description: Tell us what's on your mind
title: "[Feedback]: "
labels: ["triage"]
assignees:
  - OneSignal/eng-developer-sdk
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your valuable feedback!
  - type: textarea
    id: feedback
    attributes:
      label: What's on your mind?
      description: Feedback regarding this SDK.
      placeholder: Share your feedback...
    validations:
      required: true
