const BROWSER_TYPES = {
  'Amazon Silk' : 'amazon_silk',
  'Android Browser' : 'android',
  'Bada' : 'bada',
  'BlackBerry' : 'blackberry',
  'Chrome' : 'chrome',
  'Chromium' : 'chromium',
  'Electron' : 'electron',
  'Epiphany' : 'epiphany',
  'Firefox' : 'firefox',
  'Focus' : 'focus',
  'Generic' : 'generic',
  'Google Search' : 'google_search',
  'Googlebot' : 'googlebot',
  'Internet Explorer' : 'ie',
  'K-Meleon' : 'k_meleon',
  'Maxthon' : 'maxthon',
  'Microsoft Edge' : 'edge',
  'MZ Browser' : 'mz',
  'NAVER Whale Browser' : 'naver',
  'Opera' : 'opera',
  'Opera Coast' : 'opera_coast',
  'PhantomJS' : 'phantomjs',
  'Puffin' : 'puffin',
  'QupZilla' : 'qupzilla',
  'QQ' : 'qq',
  'QQLite' : 'qqlite',
  'Safari' : 'safari',
  'Sailfish' : 'sailfish',
  'Samsung Internet for Android' : 'samsung_internet',
  'SeaMonkey' : 'seamonkey',
  'Sleipnir' : 'sleipnir',
  'Swing' : 'swing',
  'Tizen' : 'tizen',
  'UC Browser' : 'uc',
  'Vivaldi' : 'vivaldi',
  'WebOS Browser' : 'webos',
  'WeChat' : 'wechat',
  'Yandex Browser' : 'yandex',
  'Roku' : 'roku',
};

export default BROWSER_TYPES;