/**
 * The options read-only property of the PushSubscription interface is an object containing containing
 * the options used to create the subscription.
 */
export default interface PushSubscriptionOptions {
  /**
   * A boolean, indicating that the returned push subscription will only be used for messages whose
   * effect is made visible to the user.
   */
  readonly userVisibleOnly: boolean;

  /**
   * A public key your push server will use to send messages to client apps via a push server. This
   * value is part of a signing key pair generated by your application server, and usable with
   * elliptic curve digital signature (ECDSA), over the P-256 curve.
   */
  readonly applicationServerKey: ArrayBufferLike;
}
