name: Run Tests
on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node # Since Vitest uses Node apis
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'

      - name: Bun Setup
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 'Install'
        run: bun install

      - name: 'Check Build'
        run: bun run build:prod

      - name: 'Lint'
        run: bun run lint

      - name: 'Test'
        run: bun run test
