name: Run Tests
on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: '.nvmrc'
          cache: true

      - name: Check Build
        run: vp run build:prod

      - name: Lint
        run: vp run lint

      - name: Test
        run: vp run test
